/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseCard: typeof import('./components/BaseCard.vue')['default']
    BookmarkCard: typeof import('./components/BookmarkCard.vue')['default']
    BookmarksGrid: typeof import('./components/bookmarks/BookmarksGrid.vue')['default']
    Button: typeof import('./components/ui/button/Button.vue')['default']
    Card: typeof import('./components/ui/card/Card.vue')['default']
    CardContent: typeof import('./components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./components/ui/card/CardTitle.vue')['default']
    CategoryMultiSelect: typeof import('./components/CategoryMultiSelect.vue')['default']
    Checkbox: typeof import('./components/ui/checkbox/Checkbox.vue')['default']
    ContextMenu: typeof import('./components/ContextMenu.vue')['default']
    Dialog: typeof import('./components/ui/dialog/Dialog.vue')['default']
    DialogClose: typeof import('./components/ui/dialog/DialogClose.vue')['default']
    DialogContent: typeof import('./components/ui/dialog/DialogContent.vue')['default']
    DialogDescription: typeof import('./components/ui/dialog/DialogDescription.vue')['default']
    DialogFooter: typeof import('./components/ui/dialog/DialogFooter.vue')['default']
    DialogHeader: typeof import('./components/ui/dialog/DialogHeader.vue')['default']
    DialogTitle: typeof import('./components/ui/dialog/DialogTitle.vue')['default']
    DialogTrigger: typeof import('./components/ui/dialog/DialogTrigger.vue')['default']
    FaqNotice: typeof import('./components/FaqNotice.vue')['default']
    GroupTabs: typeof import('./components/bookmarks/GroupTabs.vue')['default']
    GroupTree: typeof import('./components/GroupTree.vue')['default']
    IconSelector: typeof import('./components/IconSelector.vue')['default']
    Image: typeof import('./components/ui/image/Image.vue')['default']
    Input: typeof import('./components/ui/input/Input.vue')['default']
    Popover: typeof import('./components/ui/popover/Popover.vue')['default']
    PopoverContent: typeof import('./components/ui/popover/PopoverContent.vue')['default']
    PopoverTrigger: typeof import('./components/ui/popover/PopoverTrigger.vue')['default']
    ResultToast: typeof import('./components/ResultToast.vue')['default']
    ShareManagePanel: typeof import('./components/ShareManagePanel.vue')['default']
    SubGroupSidebar: typeof import('./components/bookmarks/SubGroupSidebar.vue')['default']
    Textarea: typeof import('./components/ui/textarea/Textarea.vue')['default']
    Tooltip: typeof import('./components/ui/tooltip/Tooltip.vue')['default']
    TooltipContent: typeof import('./components/ui/tooltip/TooltipContent.vue')['default']
    TooltipProvider: typeof import('./components/ui/tooltip/TooltipProvider.vue')['default']
    TooltipTrigger: typeof import('./components/ui/tooltip/TooltipTrigger.vue')['default']
  }
}
